services:
  gambino:
    build: .
    container_name: gambino
    restart: always
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
